import "@paradigma/styles/src/styles/global.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "@/trpc/react";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning data-oid="bcht5q1">
      <body
        className={`font-sans ${inter.variable}`}
        suppressHydrationWarning
        data-oid="jdbw_ei"
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          data-oid="c9g5hwq"
        >
          <TRPCReactProvider
            cookies={(await cookies()).toString()}
            data-oid="-x8qecu"
          >
            <main data-oid="pin-hnr">{children}</main>
            <Toaster data-oid="et._.oc" />
          </TRPCReactProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
